### ISSUE TITLE
Send updated documentation to eBird

### ISSUE THREAD

**Issue by StuartMacKay** [ProjectBabbler/ebird-api#9]
Having the [Errata](https://github.com/ProjectBabbler/ebird-api/wiki/Errata-for-the-official-eBird-API-documentation) is all very well for pointing out the errors in the [official documentation](https://documenter.getpostman.com/view/664302/S1ENwy59?version=latest#intro) but it's always a lot of work writing good documentation (and generally thankless too). Save them some work by generating updated/corrected documentation.

Update the documentation and examples for the `GET Recent observations in a region` end-point, send it to them, get feedback and continue updating the remaining end-points if they give the go-ahead.

## Tasks
- [x] Sign up for a postman account.
- [x] Create a collection from official docs. 
  Use the "Run in Postman" option.
  This took a little bit of work to set up, https://blog.getpostman.com/2018/10/16/run-in-postman-is-now-available-for-linux/
- [x] Publish the cloned collection.
  See https://documenter.getpostman.com/view/7944380/S1a7UkGE?version=latest
- [x] Update the documentation for `GET Recent observations in a region`
  See https://documenter.getpostman.com/view/7944380/S1a7UkGE?version=latest#3e0f51a3-d3ae-485f-b7b0-0a38d2f3ba99
- [x] Set up context/environment variables.
  An environment (with associated environment variables) can be selected when the documentation is published.
  - [X] Create an environment, 'ebird'.
  - [X] Include it in the publish settings.  
  - [X] Include definitions for {{serverName}} and {{contextRoot}}
  - [X] Find the nearest location to Cornell
  Sapsucker Woods--Lab Building Area, Tompkins County, New York, USA
  Location Id: L1379126
  Subnational2: US-NY-109
  Subnational1: US-NY
  Country: US 
  Lat: 42.4796874
  Lng: -76.4509829
  - [x] Create environment variables for the hierarchy of regions
  - [x] Sign up for a new api key. Add it to the environment.
 
- [x] Add examples for each of the main query parameters
- [x] Test if collection can be exported and imported.
- [x] Tell the eBird team.
  Send links, ask for feedback, ask for permission to continue the work.
  Include a description of #8. Also describe #6.
  Include the collection export as an attachment as ask them to see if it can be imported. That would make it easy to incorporate changed.
  Update: Issues 6 and 8 were not reported - the email was sufficiently long and detailed that adding more would have been confusing the to goal of getting permission to continue.

## Issues
- [X] Decide whether to include the api key header as part of the documentation or leave it as a defined variable in the request parameters.
  [Solved] Add a section for headers. The header and params in the Postman are really designed for requests made to the end-points. It's most consistent to make the documentation explicit and leave the request documentation for the examples.
